import type { Category, Product, ProductBadge } from "@/lib/types";

const img = (id: string, w = 800, h = 1000) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&q=80`;

const model = {
  a: "1544005313-94ddf0286df2",
  b: "1534528741775-53994a69daeb",
  c: "1524504388940-b1c1722653e1",
  d: "1515886657613-9f3515b0c78f",
  e: "1496747611176-843222e1e57c",
  f: "1469334031218-e382a71b716b",
  g: "1509631179647-b99d34983669",
  h: "1521572163474-6864f9cf17ab",
  i: "1483988352571-169107128987",
  j: "1503342217505-b0a15ec3261c",
};

function v(
  id: string,
  price: number,
  compare?: number,
  stock = 24,
  size = "S",
  color = "Black"
) {
  return {
    id,
    size,
    color,
    sku: `${id}-SKU`,
    price_ghs: price,
    compare_at_ghs: compare,
    stock,
  };
}

const raw: Array<{
  slug: string;
  name: string;
  desc: string;
  cat: string;
  badges: ProductBadge[];
  rating: number;
  reviews: number;
  photo: string;
  price: number;
  compare?: number;
  stock?: number;
  sizes?: string[];
  colors?: string[];
}> = [
  {
    slug: "essential-ribbed-top-black",
    name: "Essential Ribbed Top",
    desc: "A second-skin rib knit that sculpts the shoulders and waist. Designed for elevated everyday layering with a clean, confident line.",
    cat: "tops",
    badges: ["best_seller", "selling_fast"],
    rating: 4.9,
    reviews: 128,
    photo: model.a,
    price: 189,
    compare: 229,
    stock: 8,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Ivory", "Nude"],
  },
  {
    slug: "sculpted-mini-dress-ivory",
    name: "Sculpted Mini Dress",
    desc: "Structured yet fluid, with a silhouette that flatters from desk to dinner. Ivory crepe with a refined, tactile finish.",
    cat: "dresses",
    badges: ["new", "trending"],
    rating: 4.8,
    reviews: 86,
    photo: model.b,
    price: 420,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ivory", "Black"],
  },
  {
    slug: "contour-fit-set-nude",
    name: "Contour Fit Set",
    desc: "A coordinated duo that defines the waist and elongates the leg. Soft compression with a whisper of stretch for all-day ease.",
    cat: "two-piece-sets",
    badges: ["best_seller", "limited"],
    rating: 4.95,
    reviews: 204,
    photo: model.c,
    price: 395,
    compare: 460,
    stock: 5,
    sizes: ["S", "M", "L"],
    colors: ["Nude", "Espresso"],
  },
  {
    slug: "high-rise-tailored-trouser-navy",
    name: "High-Rise Tailored Trouser",
    desc: "Precision tailoring in a deep navy that reads evening or boardroom. Pressed crease, fluid drape.",
    cat: "bottoms",
    badges: ["new"],
    rating: 4.7,
    reviews: 54,
    photo: model.d,
    price: 310,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Black"],
  },
  {
    slug: "power-shoulder-blazer-suit",
    name: "Power Shoulder Blazer Suit",
    desc: "A two-piece suit with architectural shoulders and a nipped waist. For moments that require quiet authority.",
    cat: "suits",
    badges: ["limited", "trending"],
    rating: 4.85,
    reviews: 41,
    photo: model.e,
    price: 780,
    compare: 920,
    stock: 6,
    sizes: ["S", "M", "L"],
    colors: ["Black", "Charcoal"],
  },
  {
    slug: "curve-hug-denim-midwash",
    name: "Curve Hug Denim",
    desc: "Premium stretch denim with recovery that holds its shape. Mid wash with subtle whiskering for lived-in polish.",
    cat: "denim",
    badges: ["best_seller"],
    rating: 4.9,
    reviews: 312,
    photo: model.f,
    price: 265,
    sizes: ["24", "26", "28", "30", "32"],
    colors: ["Mid Wash", "Indigo"],
  },
  {
    slug: "second-skin-bodysuit-espresso",
    name: "Second-Skin Bodysuit",
    desc: "Double-layered jersey with a seamless finish. Snap closure and a neckline that frames the collarbone beautifully.",
    cat: "bodysuits",
    badges: ["new", "selling_fast"],
    rating: 4.8,
    reviews: 97,
    photo: model.g,
    price: 165,
    stock: 11,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Espresso", "Black", "Ivory"],
  },
  {
    slug: "fluid-wide-leg-jumpsuit-black",
    name: "Fluid Wide-Leg Jumpsuit",
    desc: "One-and-done dressing with a defined waist and sweeping leg. Evening-ready with minimal accessories.",
    cat: "jumpsuits",
    badges: ["trending"],
    rating: 4.75,
    reviews: 63,
    photo: model.h,
    price: 445,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Olive"],
  },
  {
    slug: "cashmere-touch-cardigan-oat",
    name: "Cashmere-Touch Cardigan",
    desc: "Featherlight knit with a brushed handle. Drapes open or belted for transitional seasons.",
    cat: "cardigans",
    badges: ["best_seller"],
    rating: 4.88,
    reviews: 142,
    photo: model.i,
    price: 298,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Oat", "Navy"],
  },
  {
    slug: "pointelle-knit-midi-dress-blush",
    name: "Pointelle Knit Midi Dress",
    desc: "Openwork texture with a modest slip lining. Feminine without feeling precious.",
    cat: "knitwear",
    badges: ["sale", "selling_fast"],
    rating: 4.65,
    reviews: 58,
    photo: model.j,
    price: 220,
    compare: 340,
    stock: 9,
    sizes: ["S", "M", "L"],
    colors: ["Blush", "Cream"],
  },
  {
    slug: "satin-bias-slip-dress-champagne",
    name: "Satin Bias Slip Dress",
    desc: "Cut on the bias for a liquid drape. Champagne satin that catches light with every step.",
    cat: "dresses",
    badges: ["new", "limited"],
    rating: 4.92,
    reviews: 74,
    photo: model.a,
    price: 510,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Champagne", "Black"],
  },
  {
    slug: "cropped-tweed-jacket-ivory",
    name: "Cropped Tweed Jacket",
    desc: "Heritage texture in a modern proportion. Pearl buttons and a clean jewel neckline.",
    cat: "tops",
    badges: ["trending"],
    rating: 4.7,
    reviews: 39,
    photo: model.b,
    price: 385,
    sizes: ["S", "M", "L"],
    colors: ["Ivory", "Black"],
  },
  {
    slug: "pleated-wide-short-espresso",
    name: "Pleated Wide Short",
    desc: "Tailored short with pressed pleats and a high waist. Vacation or city heat, equally refined.",
    cat: "bottoms",
    badges: ["new"],
    rating: 4.6,
    reviews: 28,
    photo: model.c,
    price: 198,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Espresso", "Stone"],
  },
  {
    slug: "lace-inset-blouse-white",
    name: "Lace Inset Blouse",
    desc: "Crisp poplin with lace panels at the yoke. Tuck into denim or tailoring for instant polish.",
    cat: "tops",
    badges: ["best_seller"],
    rating: 4.83,
    reviews: 112,
    photo: model.d,
    price: 245,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black"],
  },
  {
    slug: "column-maxi-dress-olive",
    name: "Column Maxi Dress",
    desc: "A long, lean column in matte jersey. Side slit for movement; bra-friendly straps.",
    cat: "dresses",
    badges: ["selling_fast"],
    rating: 4.78,
    reviews: 66,
    photo: model.e,
    price: 360,
    stock: 7,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Olive", "Black"],
  },
  {
    slug: "knit-skirt-set-midnight",
    name: "Knit Skirt Set",
    desc: "Matching crop and midi skirt in a compact rib. Travel-friendly and impossibly soft.",
    cat: "two-piece-sets",
    badges: ["new", "trending"],
    rating: 4.9,
    reviews: 91,
    photo: model.f,
    price: 418,
    sizes: ["S", "M", "L"],
    colors: ["Midnight", "Camel"],
  },
  {
    slug: "straight-leg-denim-ink",
    name: "Straight Leg Denim",
    desc: "Full-length straight with a vintage wash. High rise, minimal stretch for an authentic drape.",
    cat: "denim",
    badges: ["best_seller"],
    rating: 4.87,
    reviews: 177,
    photo: model.g,
    price: 275,
    sizes: ["24", "26", "28", "30", "32", "34"],
    colors: ["Ink", "Vintage Blue"],
  },
  {
    slug: "sculpted-bodysuit-square-neck",
    name: "Sculpted Bodysuit — Square Neck",
    desc: "Square neckline and medium coverage back. Your foundation for skirts, denim, and suiting.",
    cat: "bodysuits",
    badges: ["new"],
    rating: 4.72,
    reviews: 44,
    photo: model.h,
    price: 155,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Ivory", "Mocha"],
  },
  {
    slug: "utility-jumpsuit-stone",
    name: "Utility Jumpsuit",
    desc: "Tonal stitching, belted waist, and tapered leg. Effortless off-duty with designer intent.",
    cat: "jumpsuits",
    badges: ["sale"],
    rating: 4.55,
    reviews: 36,
    photo: model.i,
    price: 290,
    compare: 395,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Stone", "Black"],
  },
  {
    slug: "featherweight-cardigan-black",
    name: "Featherweight Cardigan",
    desc: "Ultra-fine gauge for layering under coats or over slips. Elongated cuffs.",
    cat: "cardigans",
    badges: ["best_seller", "selling_fast"],
    rating: 4.8,
    reviews: 155,
    photo: model.j,
    price: 228,
    stock: 10,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Oat", "Navy"],
  },
  {
    slug: "cable-knit-vest-ivory",
    name: "Cable Knit Vest",
    desc: "Heritage cable in a contemporary vest shape. Layer over shirting or wear alone.",
    cat: "knitwear",
    badges: ["trending"],
    rating: 4.68,
    reviews: 47,
    photo: model.a,
    price: 268,
    sizes: ["S", "M", "L"],
    colors: ["Ivory", "Camel"],
  },
  {
    slug: "asymmetric-hem-top-white",
    name: "Asymmetric Hem Top",
    desc: "Clean front, subtle drama at the hem. Pairs with slim bottoms for proportion play.",
    cat: "tops",
    badges: ["new"],
    rating: 4.62,
    reviews: 31,
    photo: model.b,
    price: 210,
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Black"],
  },
  {
    slug: "wrap-midi-dress-navy",
    name: "Wrap Midi Dress",
    desc: "True wrap with internal tie for security. Navy crepe, office-to-cocktails.",
    cat: "dresses",
    badges: ["best_seller"],
    rating: 4.85,
    reviews: 119,
    photo: model.c,
    price: 340,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Black"],
  },
  {
    slug: "tailored-short-suit-sand",
    name: "Tailored Short Suit",
    desc: "Shorts suit in warm sand. Summer events with editorial edge.",
    cat: "suits",
    badges: ["limited"],
    rating: 4.7,
    reviews: 22,
    photo: model.d,
    price: 720,
    stock: 4,
    sizes: ["S", "M", "L"],
    colors: ["Sand", "Black"],
  },
  {
    slug: "flare-denim-vintage",
    name: "Flare Denim",
    desc: "High rise flare with a clean hem. Lengthens the leg in one intentional line.",
    cat: "denim",
    badges: ["trending", "selling_fast"],
    rating: 4.77,
    reviews: 88,
    photo: model.e,
    price: 285,
    sizes: ["24", "26", "28", "30", "32"],
    colors: ["Vintage", "Black"],
  },
  {
    slug: "mesh-panel-bodysuit-black",
    name: "Mesh Panel Bodysuit",
    desc: "Strategic sheer panels with full opacity where it matters. Evening layering essential.",
    cat: "bodysuits",
    badges: ["new", "limited"],
    rating: 4.74,
    reviews: 52,
    photo: model.f,
    price: 195,
    stock: 6,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black"],
  },
  {
    slug: "belted-jumpsuit-ivory",
    name: "Belted Jumpsuit",
    desc: "Ivory twill with gold-toned hardware. Wedding guest or gallery opening.",
    cat: "jumpsuits",
    badges: ["new"],
    rating: 4.81,
    reviews: 41,
    photo: model.g,
    price: 495,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Ivory"],
  },
  {
    slug: "longline-cardigan-charcoal",
    name: "Longline Cardigan",
    desc: "Coatigan weight without bulk. Patch pockets and ribbed shawl collar.",
    cat: "cardigans",
    badges: ["best_seller"],
    rating: 4.86,
    reviews: 134,
    photo: model.h,
    price: 335,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Charcoal", "Camel"],
  },
  {
    slug: "rib-knit-dress-mocha",
    name: "Rib Knit Dress",
    desc: "Body-skimming rib with a subtle flare at the hem. Trans-seasonal staple.",
    cat: "knitwear",
    badges: ["sale"],
    rating: 4.58,
    reviews: 67,
    photo: model.i,
    price: 198,
    compare: 260,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Mocha", "Black"],
  },
  {
    slug: "new-arrivals-editorial-coat-black",
    name: "Editorial Wool Coat",
    desc: "Dropped shoulder and hidden placket. The layer that completes every outfit beneath it.",
    cat: "new-arrivals",
    badges: ["new", "limited", "trending"],
    rating: 4.93,
    reviews: 36,
    photo: model.j,
    price: 890,
    stock: 5,
    sizes: ["S", "M", "L"],
    colors: ["Black", "Camel"],
  },
];

const catNames: Record<string, string> = {
  tops: "Tops",
  dresses: "Dresses",
  "two-piece-sets": "Two-piece sets",
  bottoms: "Bottoms",
  suits: "Suits",
  denim: "Denim",
  bodysuits: "Bodysuits",
  jumpsuits: "Jumpsuits",
  cardigans: "Cardigans",
  knitwear: "Knitwear",
  "new-arrivals": "New Arrivals",
};

export const mockCategories: Category[] = [
  { slug: "tops", name: "Tops" },
  { slug: "dresses", name: "Dresses" },
  { slug: "two-piece-sets", name: "Two-piece sets" },
  { slug: "bottoms", name: "Bottoms" },
  { slug: "suits", name: "Suits" },
  { slug: "denim", name: "Denim" },
  { slug: "bodysuits", name: "Bodysuits" },
  { slug: "jumpsuits", name: "Jumpsuits" },
  { slug: "cardigans", name: "Cardigans" },
  { slug: "knitwear", name: "Knitwear" },
  { slug: "new-arrivals", name: "New Arrivals" },
];

export const mockProducts: Product[] = raw.map((p, i) => {
  const sizes = p.sizes ?? ["S", "M", "L"];
  const colors = p.colors ?? ["One"];
  const variants = sizes.flatMap((size, si) =>
    colors.map((color, ci) =>
      v(`${p.slug}-${si}-${ci}`, p.price, p.compare, p.stock ?? 20, size, color)
    )
  );
  const mainImage = img(p.photo);
  return {
    id: `mock-${i + 1}`,
    slug: p.slug,
    name: p.name,
    description: p.desc,
    category_slug: p.cat,
    category_name: catNames[p.cat] ?? p.cat,
    images: [mainImage, img(model.b), img(model.c)],
    badges: p.badges,
    rating: p.rating,
    review_count: p.reviews,
    variants,
    is_active: true,
  };
});

export function getProductBySlug(slug: string) {
  return mockProducts.find((p) => p.slug === slug);
}

export function getProductsByCategory(slug: string) {
  return mockProducts.filter((p) => p.category_slug === slug);
}

export const mockTestimonials = [
  {
    quote:
      "The ribbed top holds its shape all day. I have three colours now — it feels quietly expensive.",
    name: "Amelia K.",
    city: "Accra",
  },
  {
    quote:
      "Shipping was faster than expected and the dress looked exactly like the editorial imagery.",
    name: "Yasmine T.",
    city: "Kumasi",
  },
  {
    quote:
      "Finally a local-feeling brand with true luxury finishing. The suit tailoring is immaculate.",
    name: "Danielle R.",
    city: "London",
  },
];

export const mockOccasions = [
  { slug: "date-night", title: "Date Night", image: img(model.a) },
  { slug: "birthday", title: "Birthday", image: img(model.e) },
  { slug: "casual-chic", title: "Casual Chic", image: img(model.f) },
  { slug: "vacation", title: "Vacation", image: img(model.c) },
];
